#!/bin/bash

ps -ux | awk '{print $2" "$11}' | grep -E " /sbin" | awk '{print $2}' > files/2file
#for i in $(ls /proc/ | grep "[0-9]\+") #ps
#do
#echo $i | readlink /proc/$i/exe | grep "^/sbin" >> files/2file
#done
