#!/bin/bash
while true; do
	read line
	if [[ $line == "*" ]]
	then
		kill -USR2 $(cat .pid2)
	elif [[ $line == "+" ]]
	then
		kill -USR1 $(cat .pid2)
	elif [[ $line =~ .*TERM.* ]]
	then
		kill -SIGTERM $(cat .pid2)
		exit
	fi
done
