#!/bin/bash
echo $$ > .pid2
previousNum=1
mode="ADD"
multiply()
{
	mode="MULTIPLY"
}
add()
{
	mode="ADD"
}
end()
{
	mode="END"
}
trap 'add' USR1
trap 'multiply' USR2
trap 'end' SIGTERM
while true; do
	case $mode in
		"ADD")
			previousNum=$((previousNum+2))
			echo $previousNum
			;;
		"MULTIPLY")
			previousNum=$((previousNum*2))
			echo $previousNum
			;;
		"END")
			echo "exiting - signal from another process"
			exit
			;;
	esac
	sleep 1
done
